"""GSM8K solutions generated by *our* model, labelled the way Math-Shepherd is.

Every rate this project reports -- the 69.8% local/global gap, mu = 0.3908, the
position gradient -- comes from Math-Shepherd, whose solutions were written by
Mistral-7B-SFT. That is a different model from the one CAR would run, and a
reviewer's first question is whether the gap is a property of reasoning or a
property of one weak generator.

Answering it means rebuilding both per-step signals for a new generator:

    local   does this step's own arithmetic hold? Deterministic, and computed
            by the SAME `check_arithmetic` Math-Shepherd steps go through, so
            the two numbers are comparable by construction.
    global  does this prefix still lead to the right answer? Math-Shepherd
            estimates this by Monte-Carlo rollout ("hard estimation": `+` if
            any completion from the prefix reaches the gold answer). We do the
            same, with the generator under test as its own completer.

The output is serialised back into Math-Shepherd's exact `label` string, so
`car.data.math_shepherd.load_solutions` parses it and every downstream analysis
runs unchanged. That is the point: the Llama numbers are produced by the same
code path as the Mistral numbers, not by a parallel implementation that could
differ in a dozen small ways.

Prompting note
--------------
Few-shot exemplars are drawn from GSM8K *train* and the measurement runs on
*test*, so the model is never scored on a problem it was just shown. The
exemplars carry GSM8K's inline `<<expr=result>>` markers, which the model
imitates -- that is what makes the local check possible at all, and
`annotation_rate` reports how often it actually did so rather than assuming it.
"""

from __future__ import annotations

import random
import re
from dataclasses import dataclass

from car.data.math_shepherd import check_arithmetic

_CALC = re.compile(r"<<([^>]*?)=([^>]*?)>>")
_FINAL = re.compile(r"####\s*([-$\d.,]+)")
_NUM = re.compile(r"-?\d[\d,]*\.?\d*")

# An arithmetic claim in normalised text: an expression with at least one
# operator, then `=`, then a number. The operator requirement is what keeps
# "x = 5" and "Step 3 = done" out -- a definition is not a claim a calculator
# can refute.
_EQ = re.compile(
    r"(?<![\d.])((?:\(?-?\d+\.?\d*\)?)(?:\s*[-+*/]\s*\(?-?\d+\.?\d*\)?)+)"
    r"\s*=\s*(-?\d+\.?\d*)(?![\d.])"
)

_BS = "\\"
_LATEX_OPS = [
    (_BS + "times", "*"), (_BS + "cdot", "*"), (_BS + "div", "/"),
    ("×", "*"), ("÷", "/"),
]
_FRAC = re.compile(re.escape(_BS + "frac") + r"\{([^{}]*)\}\{([^{}]*)\}")
_LABEL = re.compile(re.escape(_BS) + r"(?:text|mathrm|boxed|mathbf)\{[^{}]*\}")
_DELIM = re.compile(re.escape(_BS) + r"[\[\]()]")
_COMMAND = re.compile(re.escape(_BS) + r"[a-zA-Z]+")

ANSWER_PREFIX = "The answer is:"


@dataclass
class GeneratedSolution:
    """One sampled solution, before global labelling."""

    example_id: str
    question: str
    gold: str
    steps: list[str]
    answer: str | None

    @property
    def final_correct(self) -> bool:
        return answers_match(self.answer, self.gold)


# ---- prompting -------------------------------------------------------


def format_exemplar(question: str, answer: str) -> str:
    return f"Question: {question.strip()}\nAnswer: {answer.strip()}"


def build_fewshot(rows: list[dict], k: int = 4, seed: int = 0) -> str:
    """Few-shot block from GSM8K train rows that carry calculator markers.

    Only annotated, multi-step exemplars are eligible: the format the model
    copies is the whole reason a local arithmetic check exists downstream.
    """
    usable = [
        r
        for r in rows
        if "<<" in r.get("answer", "") and r["answer"].count("\n") >= 2
    ]
    if len(usable) < k:
        raise ValueError(f"only {len(usable)} usable exemplars, need {k}")
    picked = random.Random(seed).sample(usable, k)
    return "\n\n".join(format_exemplar(r["question"], r["answer"]) for r in picked)


def generation_prompt(fewshot: str, question: str, prefix: list[str] | None = None) -> str:
    """Prompt for continuing a solution from `prefix` (empty = from scratch).

    Plain completion rather than a chat template, deliberately. The reported
    GSM8K numbers for these models are few-shot completion numbers, and a chat
    wrapper makes an instruct model narrate instead of imitating the exemplar
    format -- which would cost the `<<>>` markers the local check needs.
    """
    head = f"{fewshot}\n\nQuestion: {question.strip()}\nAnswer:"
    if not prefix:
        return head + " "
    return head + " " + "\n".join(s.strip() for s in prefix) + "\n"


def truncate_completion(text: str) -> str:
    """Cut a completion at the end of its own answer.

    Few-shot completion does not stop on its own: the model happily invents the
    next `Question:`. Everything from there on belongs to a different problem.
    """
    for marker in ("\nQuestion:", "\nQ:"):
        i = text.find(marker)
        if i != -1:
            text = text[:i]
    m = _FINAL.search(text)
    if m:
        text = text[: m.end()]
    return text.strip()


# ---- parsing ---------------------------------------------------------


def split_steps(solution: str) -> list[str]:
    """Solution text -> reasoning steps, excluding the `#### N` answer line."""
    steps = []
    for line in solution.splitlines():
        line = line.strip()
        if not line or line.startswith("####"):
            continue
        steps.append(line)
    return steps


def extract_answer(text: str) -> str | None:
    """The `#### N` answer, or the last number as a fallback."""
    m = _FINAL.search(text)
    raw = m.group(1) if m else None
    if raw is None:
        nums = _NUM.findall(text)
        if not nums:
            return None
        raw = nums[-1]
    return _normalise(raw)


def _normalise(raw: str) -> str | None:
    raw = raw.replace(",", "").replace("$", "").strip().rstrip(".")
    try:
        val = float(raw)
    except ValueError:
        return None
    return f"{val:g}"


def answers_match(a: str | None, b: str | None) -> bool:
    if a is None or b is None:
        return False
    na, nb = _normalise(a), _normalise(b)
    if na is None or nb is None:
        return False
    return abs(float(na) - float(nb)) < 1e-6


# ---- local validity --------------------------------------------------


def normalise_notation(text: str) -> str:
    """Rewrite LaTeX and unicode maths as plain ASCII arithmetic.

    Exists because a model's notation is not a property of its reasoning.
    Qwen2.5-7B-Instruct solves GSM8K at 80% and writes almost none of it in
    GSM8K's format:

        \\[ \\text{Miles Micah ran} = 3.5 \\times 8 = 28 \\]

    Only 14.5% of its steps carry a `<<>>` marker, against 87.8% for
    Mistral-7B-SFT, which was fine-tuned on GSM8K itself. Reading only markers
    would measure Qwen's local error on a biased seventh of its steps.
    """
    t = text
    for a, b in _LATEX_OPS:
        t = t.replace(a, b)
    t = _FRAC.sub(r"(\1)/(\2)", t)
    # \text{...} and \boxed{...} are labels, not operands. Drop them entirely
    # rather than unwrapping, or "Miles Micah ran = 28" becomes a claim.
    t = _LABEL.sub(" ~ ", t)
    t = _DELIM.sub(" ", t)
    t = _COMMAND.sub(" ", t)
    return t.replace("$", " ").replace(",", "")


def arithmetic_claims(step: str, notation: str = "marker") -> tuple[list, str]:
    """The (expression, result) pairs this step asserts, and where they came from.

    `notation="marker"` reads only `<<expr=result>>`, which is Math-Shepherd's
    definition byte for byte. `notation="any"` falls back to normalised
    LaTeX/prose when no marker is present.

    Returns (pairs, source) with source in {"marker", "derived", "none"}, so a
    caller can report how much of a corpus each path accounts for instead of
    blending them silently.
    """
    marked = [(e.strip(), r.strip()) for e, r in _CALC.findall(step)]
    if marked:
        return marked, "marker"
    if notation != "any":
        return [], "none"
    found = [(e.strip(), r.strip()) for e, r in _EQ.findall(normalise_notation(step))]
    return found, ("derived" if found else "none")


def local_validity(step: str, notation: str = "marker") -> bool | None:
    """Does this step's own arithmetic hold? None when there is none to check.

    Default `notation="marker"` is Math-Shepherd's own check, which is what
    keeps published rates stable. `notation="any"` extends coverage to models
    that do not write GSM8K's format -- and must then be applied to BOTH
    corpora, or the comparison is between two definitions rather than two
    generators. On Math-Shepherd the extension is nearly inert (87.8% -> 90.6%
    checkable, local error 0.1607 -> 0.1678), which is the evidence that it
    extends the measurement rather than redefining it.
    """
    pairs, _ = arithmetic_claims(step, notation)
    checks = [check_arithmetic(e, r) for e, r in pairs]
    checks = [c for c in checks if c is not None]
    return all(checks) if checks else None


def annotation_rate(solutions: list[GeneratedSolution]) -> float:
    """Fraction of steps carrying a `<<expr=result>>` marker.

    If this collapses, the local rate is being measured on a biased subset of
    steps and the comparison to Math-Shepherd is not sound. Worth printing
    before any headline number -- it is the gate that caught Qwen writing
    LaTeX, and without it that run would have reported a local error rate of
    0.0027 computed on a seventh of its steps.
    """
    steps = [s for sol in solutions for s in sol.steps]
    if not steps:
        return 0.0
    return sum(1 for s in steps if _CALC.search(s)) / len(steps)


def notation_breakdown(step_texts, notation: str = "any") -> dict:
    """How many steps are checkable, and via which path.

    Reported alongside every cross-generator rate. A local error rate computed
    on 41% of steps and one computed on 91% are not the same measurement, and
    the difference has to be visible rather than buried.
    """
    counts = {"marker": 0, "derived": 0, "none": 0}
    for text in step_texts:
        _, source = arithmetic_claims(text, notation)
        counts[source] += 1
    total = max(1, sum(counts.values()))
    counts["n"] = sum(counts.values())
    counts["checkable_rate"] = (counts["marker"] + counts["derived"]) / total
    return counts


# ---- serialisation back into Math-Shepherd format --------------------


def to_shepherd_label(
    question: str, steps: list[str], labels: list[bool], answer: str | None
) -> str:
    """Render one solution as Math-Shepherd's `label` string.

        {question} Step 1: {text} +\nStep 2: {text} -\n...

    Downstream code parses this rather than a bespoke schema, so the Llama and
    Mistral numbers come out of one implementation.
    """
    if len(steps) != len(labels):
        raise ValueError(f"{len(steps)} steps but {len(labels)} labels")
    body = []
    for i, (text, ok) in enumerate(zip(steps, labels, strict=True)):
        text = _sanitise(text)
        if i == len(steps) - 1 and answer is not None:
            text = f"{text} {ANSWER_PREFIX} {answer}"
        body.append(f"Step {i + 1}: {text} {'+' if ok else '-'}")
    return f"{question.strip()} " + "\n".join(body)


def _sanitise(text: str) -> str:
    """Make a step safe to embed in the `label` string.

    The step parser terminates a step at a `+`/`-` immediately followed by
    `Step N:` or end-of-string. A step whose own text ends in a bare operator
    would therefore swallow its label, so strip that; newlines would split one
    step into two, so collapse them.
    """
    text = " ".join(text.split())
    return text.rstrip("+-").rstrip() or "."


def to_shepherd_record(
    question: str, steps: list[str], labels: list[bool], answer: str | None
) -> dict:
    return {
        "task": "GSM8K",
        "label": to_shepherd_label(question, steps, labels, answer),
    }
