"""Math-Shepherd: real model-generated GSM8K solutions with per-step labels.

Why this dataset settles a question simulation cannot
-----------------------------------------------------
Math-Shepherd (Wang et al., ACL 2024, arXiv:2312.08935) contains solutions
generated by Mistral-7B-SFT, each step carrying an automatic label:

    `+`  this step has the potential to lead to the correct answer
    `-`  it does not

That label is **global** correctness -- it is derived from whether completions
from that prefix reach the right answer, so a step inherits `-` from a
corrupted premise even when the step itself is impeccable. Their own example:

    Step 2: 13 x 8 / 13 = <<13*8/13=6>>6   -   arithmetically WRONG (= 8)
    Step 3: 78 - 6 = <<78-6=72>>72         -   arithmetically CORRECT, inherits
    Step 4: 72 - 20 = 52                   -   arithmetically CORRECT, inherits

Meanwhile the inline `<<expr=result>>` annotation lets **local** validity be
checked deterministically with a calculator, no model or judge required.

Having both means the local/global gap that `car.propagation` simulates can be
measured directly on real model output, and `local_error_rate` stops being an
assumed 0.15.

Caveats worth stating in any writeup
------------------------------------
* Labels are automatic (Monte-Carlo rollout based), not human. They estimate
  "leads to the right answer", which is a *value*, not a proof of correctness.
  A lucky wrong step can be labelled `+`.
* Generator is Mistral-7B-SFT, not Llama 3.1 8B. The rates below are for that
  model; re-measure before quoting them for another one.
* Steps with no calculator annotation cannot be checked locally and are
  reported separately rather than assumed correct.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from car.verification.calculator import safe_eval

_CALC = re.compile(r"<<([^>]*?)=([^>]*?)>>")
_STEP = re.compile(r"Step\s+(\d+):\s*(.*?)\s*([+-])\s*(?=Step\s+\d+:|$)", re.S)


@dataclass
class ShepherdStep:
    index: int
    text: str
    global_ok: bool  # the `+` / `-` label
    local_ok: bool | None = None  # None when no arithmetic to check
    exprs: list[tuple[str, str]] = field(default_factory=list)

    @property
    def checkable(self) -> bool:
        return self.local_ok is not None

    @property
    def inherited_corruption(self) -> bool:
        """Locally valid but globally wrong -- the propagation signature."""
        return self.local_ok is True and not self.global_ok


@dataclass
class ShepherdSolution:
    question: str
    steps: list[ShepherdStep]

    @property
    def first_bad_index(self) -> int | None:
        for s in self.steps:
            if not s.global_ok:
                return s.index
        return None

    @property
    def first_local_error_index(self) -> int | None:
        for s in self.steps:
            if s.local_ok is False:
                return s.index
        return None

    @property
    def final_correct(self) -> bool:
        return bool(self.steps) and self.steps[-1].global_ok


def check_arithmetic(expr: str, result: str) -> bool | None:
    """Is `expr = result` arithmetically true? None when unparseable.

    Deterministic and independent of the generator -- the property that makes
    a calculator a real verifier rather than a same-model critic.
    """
    try:
        got = safe_eval(expr)
    except (ValueError, SyntaxError, ZeroDivisionError, TypeError, RecursionError):
        return None
    try:
        want = float(result.replace(",", "").strip())
    except (ValueError, AttributeError):
        return None
    if got != got or want != want:  # NaN guard
        return None
    return abs(got - want) < 1e-6


def parse_solution(label_field: str) -> ShepherdSolution | None:
    """Split a `label` field into question + labelled, locally-checked steps."""
    head, sep, rest = label_field.partition("Step 1:")
    if not sep:
        return None
    body = "Step 1:" + rest

    steps: list[ShepherdStep] = []
    for m in _STEP.finditer(body):
        idx = int(m.group(1)) - 1
        text = m.group(2).strip()
        global_ok = m.group(3) == "+"

        exprs = _CALC.findall(text)
        local_ok: bool | None = None
        if exprs:
            checks = [check_arithmetic(e, r) for e, r in exprs]
            checks = [c for c in checks if c is not None]
            # A step is locally valid only if every calculation in it holds.
            local_ok = all(checks) if checks else None

        steps.append(
            ShepherdStep(
                index=idx, text=text, global_ok=global_ok, local_ok=local_ok, exprs=exprs
            )
        )

    if not steps:
        return None
    return ShepherdSolution(question=head.strip(), steps=steps)


def load_solutions(
    path: str | Path, limit: int | None = None, stride: int = 1
) -> list[ShepherdSolution]:
    """Load GSM8K solutions.

    WARNING about `limit`: the Math-Shepherd file is sorted into contiguous
    blocks by label and by task, so a prefix of any length is close to
    single-class -- the first block is 100% wrong-answer GSM8K. Reading the
    first 20k records gives 4.8% accuracy; reading the whole strided file gives
    26.7%. Use `stride` to spread a limited read across the file rather than
    taking a prefix.
    """
    if stride < 1:
        raise ValueError("stride must be >= 1")
    out: list[ShepherdSolution] = []
    seen = 0
    with Path(path).open(encoding="utf-8") as fh:
        for line in fh:
            if limit is not None and len(out) >= limit:
                break
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if row.get("task") != "GSM8K":
                continue
            seen += 1
            if (seen - 1) % stride:
                continue
            sol = parse_solution(row.get("label", ""))
            if sol is not None:
                out.append(sol)
    return out


def class_balance(sols: list[ShepherdSolution]) -> float:
    """Fraction of solutions whose final answer is correct.

    Worth asserting before quoting any rate from this dataset: a value near 0
    or 1 means the sample landed inside one of the sorted blocks.
    """
    if not sols:
        return 0.0
    return sum(1 for s in sols if s.final_correct) / len(sols)
