"""Does the local/global gap survive a stronger generator? [CPU]

Every rate in this project came from Math-Shepherd, i.e. from Mistral-7B-SFT at
~45% on GSM8K. The standing objection is that C1 -- most globally-wrong steps
being arithmetically perfect -- is a property of one weak 2023 model, and that a
better generator would close the gap by itself.

This compares that corpus against one generated by Qwen2.5-7B-Instruct at 80%
on the same benchmark (scripts/gpu_generator_transfer.py, 500 GSM8K test
problems, 8,292 rollouts, Kaggle T4x2).

THE NOTATION PROBLEM, WHICH IS THE REASON THIS SCRIPT EXISTS

Math-Shepherd's local check reads GSM8K's `<<expr=result>>` markers. Mistral-
7B-SFT emits them in 87.8% of steps because it was fine-tuned on GSM8K itself.
Qwen emits them in 14.5% and writes the rest as LaTeX:

    \\[ \\text{Miles Micah ran} = 3.5 \\times 8 = 28 \\]

Reading only markers would measure Qwen's local error on a biased seventh of
its steps -- it reports 0.0027, which is nonsense. So both corpora are also
measured with `notation="any"`, which normalises LaTeX and prose. The check
that this extends the measurement rather than redefining it is that it barely
moves Math-Shepherd: 87.8% -> 90.6% checkable, local error 0.1607 -> 0.1678.

TWO ESTIMATORS FOR C1, BOTH REPORTED

  all-steps    inherited / global, the denominator used in the README's 69.8%.
               Unchecked steps sit in the denominator but can never enter the
               numerator, so this is biased DOWN by the uncheckable rate.
  checkable    among globally-wrong steps that can be checked at all, the
               fraction that are locally valid. Cleaner, and the one to quote
               across generators whose uncheckable rates differ by 50 points.

Run: python scripts/exp_generator_transfer.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

# `wilson` has one definition, shared with exp_rate_intervals.py, which prints
# the clustered interval beside this one. Two copies would eventually disagree,
# and the point of that comparison is that both are computed the same way.
from car.data.generated import local_validity, notation_breakdown  # noqa: E402
from car.data.math_shepherd import load_solutions  # noqa: E402
from car.eval.inference import wilson  # noqa: E402

SHEPHERD = Path("data/raw/mathshepherd/strided.jsonl")
QWEN = Path("runs/generated_qwen25_7b.jsonl")


def rows_for(path, notation):
    # No bare `limit=` on Math-Shepherd: the file is sorted into blocks by
    # label, so a prefix read is single-class. A draft of this script did that
    # and reported a baseline of 100% wrong-answer solutions.
    sols = load_solutions(path)
    out = []
    for sol in sols:
        for s in sol.steps:
            out.append({
                "final_correct": sol.final_correct,
                "global_ok": s.global_ok,
                "local_ok": local_validity(s.text, notation=notation),
                "index": s.index,
            })
    return sols, out


def stats(rows):
    n = len(rows)
    checkable = [r for r in rows if r["local_ok"] is not None]
    bad = [r for r in rows if not r["global_ok"]]
    bad_checkable = [r for r in checkable if not r["global_ok"]]
    inherited = [r for r in rows if r["local_ok"] is True and not r["global_ok"]]
    k = sum(1 for r in bad_checkable if r["local_ok"] is True)
    return {
        "n": n,
        "checkable_rate": len(checkable) / max(1, n),
        "local": sum(1 for r in checkable if r["local_ok"] is False) / max(1, len(checkable)),
        "global": len(bad) / max(1, n),
        "inherited": len(inherited) / max(1, n),
        "c1_all": len(inherited) / max(1, len(bad)),
        "c1_checkable": k / max(1, len(bad_checkable)),
        "n_bad_checkable": len(bad_checkable),
        # Wilson assumes independent steps; these are nested in solutions.
        # exp_rate_intervals.py reports the clustered interval beside it, and
        # measures that the correction here is 1.05x -- small because a
        # wrong-answer solution contributes about two of these steps.
        "ci": wilson(k, len(bad_checkable)),
    }


def block(label, sols, rows):
    print(f"\n  {label}")
    print(f"    {'stratum':<24}{'steps':>8}{'chk':>7}{'local':>8}{'global':>8}"
          f"{'inher':>8}{'C1 all':>8}{'C1 chk':>8}{'n bad':>8}")
    print("    " + "-" * 79)
    for name, sel in (("final answer CORRECT", lambda r: r["final_correct"]),
                      ("final answer WRONG", lambda r: not r["final_correct"]),
                      ("whole sample", lambda r: True)):
        g = [r for r in rows if sel(r)]
        if not g:
            continue
        s = stats(g)
        print(f"    {name:<24}{s['n']:>8,}{s['checkable_rate']:>7.1%}"
              f"{s['local']:>8.4f}{s['global']:>8.4f}{s['inherited']:>8.4f}"
              f"{s['c1_all']:>8.4f}{s['c1_checkable']:>8.4f}"
              f"{s['n_bad_checkable']:>8,}")
    return stats([r for r in rows if not r["final_correct"]])


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--shepherd", type=Path, default=SHEPHERD)
    ap.add_argument("--generated", type=Path, default=QWEN)
    args = ap.parse_args()

    for p in (args.shepherd, args.generated):
        if not p.exists():
            print(f"missing {p}")
            return 1

    corpora = [
        ("Mistral-7B-SFT  (Math-Shepherd)", args.shepherd),
        ("Qwen2.5-7B-Instruct (generated)", args.generated),
    ]

    print("=" * 88)
    print("NOTATION: what fraction of steps can be checked at all")
    print("=" * 88)
    print("The local check is only as good as its coverage. A rate computed on")
    print("91% of steps and one computed on 41% are not the same measurement.\n")
    print(f"  {'corpus':<34}{'notation':<10}{'marker':>9}{'derived':>9}"
          f"{'none':>9}{'checkable':>11}")
    print("  " + "-" * 82)
    loaded = {}
    for label, path in corpora:
        for notation in ("marker", "any"):
            sols, rows = rows_for(path, notation)
            loaded[(label, notation)] = (sols, rows)
            texts = [s.text for sol in sols for s in sol.steps]
            b = notation_breakdown(texts, notation)
            print(f"  {label:<34}{notation:<10}{b['marker']:>9,}{b['derived']:>9,}"
                  f"{b['none']:>9,}{b['checkable_rate']:>11.1%}")

    print()
    print("=" * 88)
    print("PER-STEP RATES")
    print("=" * 88)
    print("C1 all  = inherited / global over ALL steps (the README's 69.8%)")
    print("C1 chk  = among globally-wrong CHECKABLE steps, the fraction locally valid")

    summary = {}
    for notation in ("marker", "any"):
        print(f"\n{'-' * 88}")
        print(f"notation = {notation}")
        for label, _ in corpora:
            sols, rows = loaded[(label, notation)]
            summary[(label, notation)] = block(label, sols, rows)

    print()
    print("=" * 88)
    print("THE COMPARISON, on the definition that applies to both")
    print("=" * 88)
    a = summary[(corpora[0][0], "any")]
    b = summary[(corpora[1][0], "any")]
    print("Within wrong-answer solutions, notation='any':\n")
    print(f"  {'':<32}{'Mistral-7B-SFT':>18}{'Qwen2.5-7B':>14}")
    print("  " + "-" * 64)
    for key, name in (("local", "local error"), ("global", "global error"),
                      ("c1_checkable", "C1 (checkable)")):
        print(f"  {name:<32}{a[key]:>18.4f}{b[key]:>14.4f}")
    print(f"  {'n globally-wrong checkable':<32}{a['n_bad_checkable']:>18,}"
          f"{b['n_bad_checkable']:>14,}")
    ci_a = f"[{a['ci'][0]:.3f}, {a['ci'][1]:.3f}]"
    ci_b = f"[{b['ci'][0]:.3f}, {b['ci'][1]:.3f}]"
    print(f"  {'95% CI on C1 (Wilson)':<32}{ci_a:>18}{ci_b:>16}")
    print()
    if b["c1_checkable"] > a["c1_checkable"]:
        print("  C1 is HIGHER on the stronger generator. The objection this")
        print("  experiment tests -- that the gap is an artifact of a weak model --")
        print("  is refuted, and in the direction that strengthens the thesis: a")
        print("  better generator makes fewer arithmetic slips, so MORE of what")
        print("  remains is inherited corruption a calculator cannot see.")
    else:
        print("  C1 is lower on the stronger generator; the gap is at least")
        print("  partly a property of generator strength.")
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
